from .combat.combat import OSRSCombat
from .woodcutter import OSRSWoodcutter
from .fisher import OSRSFisher
from .miner import OSRSMiner
from .smelter import OSRSSmelter
from .runner import OSRSRunner
from .constructor import OSRSConstructor
from .fletcher import OSRSFletcher
from .thief import OSRSThief